apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-container
        image: https://github.com/Haru1706/container/tree/main/note-app:latest
        ports:
        - containerPort: 5000
